version: "3"

services:
  app:
    build:
      context: . # to the current directory
    ports:
      - "9000:9000"
    volumes:
      - ./app:/app #map the current directory to the app in the container
    command: >
      sh -c "python manage.py wait_for_db && 
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:9000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=maotrix1
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=maotrix1
