# Generated by Django 3.1.1 on 2020-09-25 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe_image'),
        ('core', '0002_user_logout'),
    ]

    operations = [
    ]
